Dim speaks, speech, speaks2, speaks3
speaks="HE TERMINADO. PERO NO PUDE ENCONTRAR LA CLAVE"
speaks2="PRUEBA CON OTRO DICCIONARIO, O ESPERA A QUE MI CREADOR GENERE UN ALGORITMO QUE PRUEBE TODAS LAS COMBINACIONES POSIBLES DE TODOS LOS CARACTERES EXISTENTES"
speaks3="ACTUALMENTE ESTAMOS EN LA VERSION MAS ESTABLE DEL PROGRAMA, Y TE PUEDO ASEGURAR QUE TENDRA UNA MEJOR VERSION DENTRO DE POCO EN LA CUAL SE AGREGUEN DICCIONARIOS"
Set speech=CreateObject("sapi.spvoice")
speech.Speak speaks
WScript.Sleep (100)
speech.Speak speaks2
WScript.Sleep (500)
speech.Speak speaks3